name: Release Drafter

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d.%H%M%S')"
      - uses: release-drafter/release-drafter@v5
        with:
          config-name: templates/release-drafter.yml
          name: ${{ steps.date.outputs.date }} リリース
          tag: ${{ steps.date.outputs.date }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
